apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: oliva-telegram
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: olivia-telegram
    type: web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  labels:
    app: oliva-telegram
spec:
  ports:
    - port: 8011
      protocol: TCP
      targetPort: 8011
  selector:
    app: olivia-telegram
    type: bot
  type: ClusterIP
