apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-col-stat
  annotations:
    # Hooks define job order execution
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: collectstatic
          image: {{ pluck .Values.global.env .Values.image.django.repository | first }}:{{ pluck .Values.global.env .Values.image.django.tag | first }} 
          imagePullPolicy: {{ pluck .Values.global.env .Values.image.django.pullPolicy | first }}
          command: {{ .Values.command.collectstatic }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "app.settings"
          volumeMounts:
            - name: static
              mountPath: /static
            - name: envfile
              mountPath: /app/.env
              subPath: .env
      restartPolicy: Never
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end}}
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: envfile
          configMap:
            name: django-config
  backoffLimit: 5
