apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ pluck .Values.global.env .Values.pvc.static.storage | first }}
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ pluck .Values.global.env .Values.pvc.media.storage | first }}
  storageClassName: aws-efs
